### ISSUE TITLE
Gold module disappear from bar when "Show Free Bag Space" is unchecked.

### ISSUE THREAD

**Issue by Fantazyjny** [MilleXIV/XIV_Databar#44] opened 2016-09-03 12:20 UTC
**Lua Error**
```
Message: Interface\AddOns\XIV_Databar\modules\gold.lua:83: <unnamed>:SetText(): Font not set
Time: 09/03/16 14:08:58
Count: 1
Stack: (tail call): ?
[C]: in function `SetText'
Interface\AddOns\XIV_Databar\modules\gold.lua:82: in function `Refresh'
Interface\AddOns\XIV_Databar\modules\gold.lua:31: in function <Interface\AddOns\XIV_Databar\modules\gold.lua:19>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:993: in function <Interface\FrameXML\UIParent.lua:891>

Locals: <none>
```

**Fixed by adding:** 
`self.bagText:SetFont(xb:GetFont(db.text.fontSize))`
abve line 82 in gold.lua

**Comment by MilleXIV** [comment] 2016-09-04 13:47
Duplicate of #35, fixed but not pushed yet.

**Closed by MilleXIV** 2016-09-04 13:47 UTC
Labels: duplicate

**Comment by Vegeir** [comment] 2016-09-05 20:33
self.bagText:SetFont(xb:GetFont(db.text.fontSize))

is still missing from 2.04 and 2.05.  I lose my gold setting as soon as I update until I add this code in the else function above line 82.
